// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElMenuItemGroup: typeof import("element-plus/es")["ElMenuItemGroup"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSubmenu: typeof import("element-plus/es")["ElSubmenu"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    Hamburger: typeof import("./src/components/Hamburger/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}

export {};
