// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Breadcrumb: typeof import("./../components/Breadcrumb/index.vue")["default"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    Hamburger: typeof import("./../components/Hamburger/index.vue")["default"];
    ICilLanguage: typeof import("~icons/cil/language")["default"];
    LangSelect: typeof import("./../components/LangSelect/index.vue")["default"];
    Pagination: typeof import("./../components/Pagination/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}

export {};
